# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestegiulianaflores():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(2)
    self.driver.maximize_window()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testegiulianaflores(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.find_element(By.CSS_SELECTOR, "#perfil-hidden > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    self.driver.find_element(By.ID, "ContentSite_txtEmail").send_keys("bernar_otavio_ribeiro@hersa.com.br")
    self.driver.find_element(By.ID, "ContentSite_txtPassword").send_keys("123456789ABcd")
    self.driver.find_element(By.ID, "ContentSite_ibtContinue").click()
    self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-active .img_banner").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".swiper-slide-active .img_banner")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) > .product-item img").click()
    self.driver.find_element(By.ID, "ContentSite_lbtBuy").click()
    self.driver.find_element(By.ID, "ContentSite_uwcCalendar_txtZip").click()
    self.driver.find_element(By.ID, "ContentSite_uwcCalendar_txtZip").send_keys("01320")
    self.driver.find_element(By.ID, "ContentSite_uwcCalendar_txtZipComplement").send_keys("000")
    self.driver.find_element(By.CSS_SELECTOR, ".jSelectZip").click()
    self.driver.execute_script("window.scrollTo(0,282)")
    self.driver.execute_script("window.scrollTo(0,289)")
    self.driver.find_element(By.ID, "btConfirmShippingData").click()
    self.driver.find_element(By.ID, "ContentSite_lbtBuy").click()
    self.driver.find_element(By.ID, "ContentSite_Basketcontrol1_rptBasket_imbFinalize_0").click()
    self.driver.find_element(By.ID, "btnContinue").click()
    self.driver.execute_script("window.scrollTo(0,1502)")
    self.driver.find_element(By.ID, "txtDsDestinationName").click()
    self.driver.find_element(By.ID, "txtDsDestinationName").send_keys("Johnny")
    self.driver.find_element(By.ID, "txtDsNumber").click()
    self.driver.find_element(By.ID, "txtDsNumber").send_keys("355")
    self.driver.find_element(By.ID, "ContentSite_rptDeliveryAddress_rbtFgPersonalAddress_0_0_0").click()
    self.driver.find_element(By.ID, "btnContinue").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".chamadaPagamento").text == "Selecione a forma de pagamento de sua preferência"
    self.driver.close()
  
