# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestegiulianaflores():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(2)
    self.driver.maximize_window()
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testegiulianaflores(self):
    self.driver.get("https://www.giulianaflores.com.br/")
    self.driver.find_element(By.CSS_SELECTOR, "#perfil-hidden > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "#UrlLogin > a").click()
    time.sleep(2)
    self.driver.find_element(By.ID, "ContentSite_ibtNewCustomer").click()
    self.driver.find_element(By.NAME, "ctl00$ContentSite$txtName").send_keys("Bernardo Otavio Iago Ribeiro ")
    self.driver.find_element(By.NAME, "ctl00$ContentSite$txtCpf").send_keys("693.032.710-76")
    self.driver.find_element(By.NAME, "ctl00$ContentSite$txtEmail").send_keys("bernar_otavio_ribeiro@hersa.com.br")
    self.driver.find_element(By.NAME, "ctl00$ContentSite$txtPasswordNew").send_keys("123456789ABcd")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtZip").send_keys("61932-500")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_btnAddressFind").click()
    self.driver.find_element(By.NAME, "ctl00$ContentSite$CustomerAddress$txtAddressNumber").send_keys("250")
    self.driver.find_element(By.ID, "ContentSite_CustomerAddress_txtPhoneCelularNum").send_keys("11952348954")
    self.driver.find_element(By.ID,"ContentSite_btnCreateCustomer").click()
    self.driver.close()
  
